package main // https://dev.to/incrypt0/simple-telegram-bot-in-go-28ek

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"net/http"
	"strings"
)

// The webHook request body type
type webHookReqBody struct {
	Message struct {
		Text string `json:"text"`
		Chat struct {
			ID int64 `json:"id"`
		} `json:"chat"`
	} `json:"message"`
}

// The request tempelate for an outgoing message
type sendMessageReqBody struct {
	ChatID int64  `json:"chat_id"`
	Text   string `json:"text"`
}

// stuct representing a joke
type joke struct {
	Value struct {
		Joke string `json:"joke"`
	} `json:"value"`
}

// our telegram bot toke generated by botfather
const botToken = "985992724:AAF9l3-4GpA3pVxVEbvQy_nuoefg3dSddA4"

func main() {
	err := http.ListenAndServe(":8080", http.HandlerFunc(webHookHandler))
	if err != nil {
		log.Fatal(err)
		return
	}
}

// This function is called whenever an update is recieved
func webHookHandler(rw http.ResponseWriter, req *http.Request) {
	// Create our web hook request body type instance
	body := &webHookReqBody{}

	// Decodes the incoming request into our cutom webhookreqbody type
	if err := json.NewDecoder(req.Body).Decode(body); err != nil {
		log.Printf("An error occured (webHookHandler)")
		log.Panic(err)
		return
	}

	// If the command /joke is recieved call the sendReply function
	if strings.ToLower(body.Message.Text) == "/joke" {
		err := sendReply(body.Message.Chat.ID)
		if err != nil {
			log.Panic(err)
			return
		}
	}
}

// sends joke replies
func sendReply(chatID int64) error {
	fmt.Println("sendReply called")

	// calls the joke fetcher fucntion and gets a random joke from the API
	text, err := jokeFetcher()
	if err != nil {
		return err
	}

	//Creates an instance of our custom sendMessageReqBody Type
	reqBody := &sendMessageReqBody{
		ChatID: chatID,
		Text:   text,
	}

	// Convert our custom type into json format
	reqBytes, err := json.Marshal(reqBody)
	if err != nil {
		return err
	}

	// Make a request to send our message using the POST method to the telegram bot API
	resp, err := http.Post(
		"https://api.telegram.org/bot"+botToken+"/"+"sendMessage",
		"application/json",
		bytes.NewBuffer(reqBytes),
	)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return errors.New("unexpected status" + resp.Status)
	}

	return err
}

// fetches the joke from api and decodes it into our custom joke type
func jokeFetcher() (string, error) {
	resp, err := http.Get("http://api.icndb.com/jokes/random")
	c := &joke{}
	if err != nil {
		return "", err
	}
	err = json.NewDecoder(resp.Body).Decode(c)
	return c.Value.Joke, err
}
