CREATE TABLE `amazon_ca_fba_order` (
	`amazon_order_id` VARCHAR(40) NOT NULL,
	`merchant_order_id` VARCHAR(40) NOT NULL,
	`shipment_id` VARCHAR(40) NOT NULL,
	`shipment_item_id` VARCHAR(40) NOT NULL,
	`amazon_order_item_id` VARCHAR(40) NOT NULL,
	`merchant_order_item_id` VARCHAR(40) NOT NULL,
	`purchase_date` DATETIME NOT NULL,
	`payments_date` DATETIME NOT NULL,
	`shipment_date` DATETIME NOT NULL,
	`reporting_date` DATETIME NOT NULL,
	`buyer_email` VARCHAR(40) NOT NULL,
	`buyer_name` VARCHAR(40) NOT NULL,
	`buyer_phone_number` VARCHAR(20) NOT NULL,
	`sku` VARCHAR(40) NOT NULL,
	`product_name` VARCHAR(80) NOT NULL,
	`quantity_shipped` VARCHAR(10) NOT NULL,
	`currency` VARCHAR(10) NOT NULL,
	`item_price` VARCHAR(10) NOT NULL,
	`item_tax` VARCHAR(10) NOT NULL,
	`shipping_price` VARCHAR(10) NOT NULL,
	`shipping_tax` VARCHAR(10) NOT NULL,
	`gift_wrap_price` VARCHAR(10) NOT NULL,
	`gift_wrap_tax` VARCHAR(10) NOT NULL,
	`ship_service_level` VARCHAR(20) NOT NULL,
	`recipient_name` VARCHAR(40) NOT NULL,
	`ship_address_1` VARCHAR(80) NOT NULL,
	`ship_address_2` VARCHAR(80) NOT NULL,
	`ship_address_3` VARCHAR(80) NOT NULL,
	`ship_city` VARCHAR(40) NOT NULL,
	`ship_state` VARCHAR(20) NOT NULL,
	`ship_postal_code` VARCHAR(40) NOT NULL,
	`ship_country` VARCHAR(10) NOT NULL,
	`ship_phone_number` VARCHAR(20) NOT NULL,
	`bill_address_1` VARCHAR(80) NOT NULL,
	`bill_address_2` VARCHAR(80) NOT NULL,
	`bill_address_3` VARCHAR(80) NOT NULL,
	`bill_city` VARCHAR(40) NOT NULL,
	`bill_state` VARCHAR(20) NOT NULL,
	`bill_postal_code` VARCHAR(20) NOT NULL,
	`bill_country` VARCHAR(10) NOT NULL,
	`item_promotion_discount` VARCHAR(10) NOT NULL,
	`ship_promotion_discount` VARCHAR(10) NOT NULL,
	`carrier` VARCHAR(20) NOT NULL,
	`tracking_number` VARCHAR(40) NOT NULL,
	`estimated_arrival_date` DATETIME NOT NULL,
	`fulfillment_center_id` VARCHAR(10) NOT NULL,
	`fulfillment_channel` VARCHAR(10) NOT NULL,
	`sales_channel` VARCHAR(20) NOT NULL,
	PRIMARY KEY (`amazon_order_id`),
	INDEX `sku` (`sku`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

-- Split one table into two

CREATE TABLE `amazon_ca_fba_order` (
	`amazon_order_id` VARCHAR(40) NOT NULL,
	`merchant_order_id` VARCHAR(40) NOT NULL,
	`shipment_id` VARCHAR(40) NOT NULL,
	`purchase_date` DATETIME NOT NULL,
	`payments_date` DATETIME NOT NULL,
	`shipment_date` DATETIME NOT NULL,
	`reporting_date` DATETIME NOT NULL,
	`buyer_email` VARCHAR(40) NOT NULL,
	`buyer_name` VARCHAR(40) NOT NULL,
	`buyer_phone_number` VARCHAR(20) NOT NULL,
	`recipient_name` VARCHAR(40) NOT NULL,
	`ship_address_1` VARCHAR(80) NOT NULL,
	`ship_address_2` VARCHAR(80) NOT NULL,
	`ship_address_3` VARCHAR(80) NOT NULL,
	`ship_city` VARCHAR(40) NOT NULL,
	`ship_state` VARCHAR(20) NOT NULL,
	`ship_postal_code` VARCHAR(40) NOT NULL,
	`ship_country` VARCHAR(10) NOT NULL,
	`ship_phone_number` VARCHAR(20) NOT NULL,
	`bill_address_1` VARCHAR(80) NOT NULL,
	`bill_address_2` VARCHAR(80) NOT NULL,
	`bill_address_3` VARCHAR(80) NOT NULL,
	`bill_city` VARCHAR(40) NOT NULL,
	`bill_state` VARCHAR(20) NOT NULL,
	`bill_postal_code` VARCHAR(20) NOT NULL,
	`bill_country` VARCHAR(10) NOT NULL,
	`sales_channel` VARCHAR(20) NOT NULL,
	PRIMARY KEY (`amazon_order_id`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE `amazon_ca_fba_order_item` (
	`amazon_order_id` VARCHAR(40) NOT NULL,
	`shipment_item_id` VARCHAR(40) NOT NULL,
	`amazon_order_item_id` VARCHAR(40) NOT NULL,
	`merchant_order_item_id` VARCHAR(40) NOT NULL,
	`sku` VARCHAR(40) NOT NULL,
	`product_name` VARCHAR(80) NOT NULL,
	`quantity_shipped` VARCHAR(10) NOT NULL,
	`item_price` VARCHAR(10) NOT NULL,
	`item_tax` VARCHAR(10) NOT NULL,
	`shipping_price` VARCHAR(10) NOT NULL,
	`shipping_tax` VARCHAR(10) NOT NULL,
	`gift_wrap_price` VARCHAR(10) NOT NULL,
	`gift_wrap_tax` VARCHAR(10) NOT NULL,
	`item_promotion_discount` VARCHAR(10) NOT NULL,
	`ship_promotion_discount` VARCHAR(10) NOT NULL,
	`currency` VARCHAR(10) NOT NULL,
	`carrier` VARCHAR(20) NOT NULL,
	`ship_service_level` VARCHAR(20) NOT NULL,
	`tracking_number` VARCHAR(40) NOT NULL,
	`estimated_arrival_date` DATETIME NOT NULL,
	`fulfillment_center_id` VARCHAR(10) NOT NULL,
	`fulfillment_channel` VARCHAR(10) NOT NULL,
	INDEX `amazon_order_id` (`amazon_order_id`),
	INDEX `sku` (`sku`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB;
