CREATE TABLE `amazon_lowest_offer_listings` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`MarketplaceId` VARCHAR(20) NULL DEFAULT NULL,
	`SellerId` VARCHAR(20) NULL DEFAULT NULL,
	`SellerSKU` VARCHAR(40) NULL DEFAULT NULL,
	`ASIN` VARCHAR(20) NULL DEFAULT NULL,
	`AllOfferListingsConsidered` VARCHAR(20) NULL DEFAULT NULL,
	`ItemCondition` VARCHAR(20) NULL DEFAULT NULL,
	`ItemSubcondition` VARCHAR(20) NULL DEFAULT NULL,
	`FulfillmentChannel` VARCHAR(20) NULL DEFAULT NULL,
	`ShipsDomestically` VARCHAR(20) NULL DEFAULT NULL,
	`ShippingTime` VARCHAR(20) NULL DEFAULT NULL,
	`SellerPositiveFeedbackRating` VARCHAR(20) NULL DEFAULT NULL,
	`NumberOfOfferListingsConsidered` VARCHAR(20) NULL DEFAULT NULL,
	`SellerFeedbackCount` VARCHAR(20) NULL DEFAULT NULL,
	`MultipleOffersAtLowestPrice` VARCHAR(20) NULL DEFAULT NULL,
	`LandedPrice` VARCHAR(20) NULL DEFAULT NULL,
	`ListingPrice` VARCHAR(20) NULL DEFAULT NULL,
	`Shipping` VARCHAR(20) NULL DEFAULT NULL,
	`CurrencyCode` VARCHAR(20) NULL DEFAULT NULL,
	`createdon` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
