<?php

namespace Kanboard\Core;

use Pimple\Container;

/**
 * Base Class
 *
 * \Kanboard\Analytic\TaskDistributionAnalytic             $taskDistributionAnalytic
 * \Kanboard\Analytic\UserDistributionAnalytic             $userDistributionAnalytic
 * \Kanboard\Analytic\EstimatedTimeComparisonAnalytic      $estimatedTimeComparisonAnalytic
 * \Kanboard\Analytic\AverageLeadCycleTimeAnalytic         $averageLeadCycleTimeAnalytic
 * \Kanboard\Analytic\AverageTimeSpentColumnAnalytic       $averageTimeSpentColumnAnalytic
 * \Kanboard\Core\Action\ActionManager                     $actionManager
 * \Kanboard\Core\ExternalLink\ExternalLinkManager         $externalLinkManager
 * \Kanboard\Core\ExternalTask\ExternalTaskManager         $externalTaskManager
 * \Kanboard\Core\Cache\MemoryCache                        $memoryCache
 * \Kanboard\Core\Cache\BaseCache                          $cacheDriver
 * \Kanboard\Core\Event\EventManager                       $eventManager
 * \Kanboard\Core\Group\GroupManager                       $groupManager
 * \Kanboard\Core\User\UserManager                         $userManager
 * \Kanboard\Core\Http\Client                              $httpClient
 * \Kanboard\Core\Http\OAuth2                              $oauth
 * \Kanboard\Core\Http\RememberMeCookie                    $rememberMeCookie
 * \Kanboard\Core\Http\Request                             $request
 * \Kanboard\Core\Http\Response                            $response
 * \Kanboard\Core\Http\Router                              $router
 * \Kanboard\Core\Http\Route                               $route
 * \Kanboard\Core\Queue\QueueManager                       $queueManager
 * \Kanboard\Core\Mail\Client                              $emailClient
 * \Kanboard\Core\ObjectStorage\ObjectStorageInterface     $objectStorage
 * \Kanboard\Core\Plugin\Hook                              $hook
 * \Kanboard\Core\Plugin\Loader                            $pluginLoader
 * \Kanboard\Core\Security\AuthenticationManager           $authenticationManager
 * \Kanboard\Core\Security\AccessMap                       $applicationAccessMap
 * \Kanboard\Core\Security\AccessMap                       $projectAccessMap
 * \Kanboard\Core\Security\AccessMap                       $apiAccessMap
 * \Kanboard\Core\Security\AccessMap                       $apiProjectAccessMap
 * \Kanboard\Core\Security\Authorization                   $applicationAuthorization
 * \Kanboard\Core\Security\Authorization                   $projectAuthorization
 * \Kanboard\Core\Security\Authorization                   $apiAuthorization
 * \Kanboard\Core\Security\Authorization                   $apiProjectAuthorization
 * \Kanboard\Core\Security\Role                            $role
 * \Kanboard\Core\Security\Token                           $token
 * \Kanboard\Core\Session\FlashMessage                     $flash
 * \Kanboard\Core\Session\SessionManager                   $sessionManager
 * \Kanboard\Core\User\Avatar\AvatarManager                $avatarManager
 * \Kanboard\Core\User\GroupSync                           $groupSync
 * \Kanboard\Core\User\UserProfile                         $userProfile
 * \Kanboard\Core\User\UserSync                            $userSync
 * \Kanboard\Core\User\UserSession                         $userSession
 * \Kanboard\Core\DateParser                               $dateParser
 * \Kanboard\Core\Helper                                   $helper
 * \Kanboard\Core\Paginator                                $paginator
 * \Kanboard\Core\Template                                 $template
 * \Kanboard\Decorator\MetadataCacheDecorator              $userMetadataCacheDecorator
 * \Kanboard\Decorator\UserCacheDecorator                  $userCacheDecorator
 * \Kanboard\Decorator\ColumnRestrictionCacheDecorator     $columnRestrictionCacheDecorator
 * \Kanboard\Decorator\ColumnMoveRestrictionCacheDecorator $columnMoveRestrictionCacheDecorator
 * \Kanboard\Decorator\ProjectRoleRestrictionCacheDecorator $projectRoleRestrictionCacheDecorator
 * \Kanboard\Formatter\BoardColumnFormatter                $boardColumnFormatter
 * \Kanboard\Formatter\BoardFormatter                      $boardFormatter
 * \Kanboard\Formatter\BoardSwimlaneFormatter              $boardSwimlaneFormatter
 * \Kanboard\Formatter\BoardTaskFormatter                  $boardTaskFormatter
 * \Kanboard\Formatter\GroupAutoCompleteFormatter          $groupAutoCompleteFormatter
 * \Kanboard\Formatter\ProjectActivityEventFormatter       $projectActivityEventFormatter
 * \Kanboard\Formatter\ProjectApiFormatter                 $projectApiFormatter
 * \Kanboard\Formatter\ProjectsApiFormatter                $projectsApiFormatter
 * \Kanboard\Formatter\SubtaskListFormatter                $subtaskListFormatter
 * \Kanboard\Formatter\SubtaskTimeTrackingCalendarFormatter $subtaskTimeTrackingCalendarFormatter
 * \Kanboard\Formatter\TaskApiFormatter                    $taskApiFormatter
 * \Kanboard\Formatter\TasksApiFormatter                   $tasksApiFormatter
 * \Kanboard\Formatter\TaskAutoCompleteFormatter           $taskAutoCompleteFormatter
 * \Kanboard\Formatter\TaskICalFormatter                   $taskICalFormatter
 * \Kanboard\Formatter\TaskListFormatter                   $taskListFormatter
 * \Kanboard\Formatter\TaskListSubtaskFormatter            $taskListSubtaskFormatter
 * \Kanboard\Formatter\TaskListSubtaskAssigneeFormatter    $taskListSubtaskAssigneeFormatter
 * \Kanboard\Formatter\TaskSuggestMenuFormatter            $taskSuggestMenuFormatter
 * \Kanboard\Formatter\UserAutoCompleteFormatter           $userAutoCompleteFormatter
 * \Kanboard\Formatter\UserMentionFormatter                $userMentionFormatter
 * \Kanboard\Model\ActionModel                             $actionModel
 * \Kanboard\Model\ActionParameterModel                    $actionParameterModel
 * \Kanboard\Model\AvatarFileModel                         $avatarFileModel
 * \Kanboard\Model\BoardModel                              $boardModel
 * \Kanboard\Model\CategoryModel                           $categoryModel
 * \Kanboard\Model\ColorModel                              $colorModel
 * \Kanboard\Model\ColumnModel                             $columnModel
 * \Kanboard\Model\ColumnRestrictionModel                  $columnRestrictionModel
 * \Kanboard\Model\ColumnMoveRestrictionModel              $columnMoveRestrictionModel
 * \Kanboard\Model\CommentModel                            $commentModel
 * \Kanboard\Model\ConfigModel                             $configModel
 * \Kanboard\Model\CurrencyModel                           $currencyModel
 * \Kanboard\Model\CustomFilterModel                       $customFilterModel
 * \Kanboard\Model\TaskFileModel                           $taskFileModel
 * \Kanboard\Model\ProjectFileModel                        $projectFileModel
 * \Kanboard\Model\GroupModel                              $groupModel
 * \Kanboard\Model\GroupMemberModel                        $groupMemberModel
 * \Kanboard\Model\InviteModel                             $inviteModel
 * \Kanboard\Model\LanguageModel                           $languageModel
 * \Kanboard\Model\LastLoginModel                          $lastLoginModel
 * \Kanboard\Model\LinkModel                               $linkModel
 * \Kanboard\Model\NotificationModel                       $notificationModel
 * \Kanboard\Model\PasswordResetModel                      $passwordResetModel
 * \Kanboard\Model\PredefinedTaskDescriptionModel          $predefinedTaskDescriptionModel
 * \Kanboard\Model\ProjectModel                            $projectModel
 * \Kanboard\Model\ProjectActivityModel                    $projectActivityModel
 * \Kanboard\Model\ProjectDuplicationModel                 $projectDuplicationModel
 * \Kanboard\Model\ProjectDailyColumnStatsModel            $projectDailyColumnStatsModel
 * \Kanboard\Model\ProjectDailyStatsModel                  $projectDailyStatsModel
 * \Kanboard\Model\ProjectMetadataModel                    $projectMetadataModel
 * \Kanboard\Model\ProjectPermissionModel                  $projectPermissionModel
 * \Kanboard\Model\ProjectUserRoleModel                    $projectUserRoleModel
 * \Kanboard\Model\ProjectGroupRoleModel                   $projectGroupRoleModel
 * \Kanboard\Model\ProjectNotificationModel                $projectNotificationModel
 * \Kanboard\Model\ProjectNotificationTypeModel            $projectNotificationTypeModel
 * \Kanboard\Model\ProjectRoleModel                        $projectRoleModel
 * \Kanboard\Model\ProjectRoleRestrictionModel             $projectRoleRestrictionModel
 * \Kanboard\Model\ProjectTaskDuplicationModel             $projectTaskDuplicationModel
 * \Kanboard\Model\ProjectTaskPriorityModel                $projectTaskPriorityModel
 * \Kanboard\Model\RememberMeSessionModel                  $rememberMeSessionModel
 * \Kanboard\Model\SubtaskModel                            $subtaskModel
 * \Kanboard\Model\SubtaskPositionModel                    $subtaskPositionModel
 * \Kanboard\Model\SubtaskStatusModel                      $subtaskStatusModel
 * \Kanboard\Model\SubtaskTaskConversionModel              $subtaskTaskConversionModel
 * \Kanboard\Model\SubtaskTimeTrackingModel                $subtaskTimeTrackingModel
 * \Kanboard\Model\SwimlaneModel                           $swimlaneModel
 * \Kanboard\Model\TagDuplicationModel                     $tagDuplicationModel
 * \Kanboard\Model\TagModel                                $tagModel
 * \Kanboard\Model\TaskModel                               $taskModel
 * \Kanboard\Model\TaskAnalyticModel                       $taskAnalyticModel
 * \Kanboard\Model\TaskCreationModel                       $taskCreationModel
 * \Kanboard\Model\TaskDuplicationModel                    $taskDuplicationModel
 * \Kanboard\Model\TaskProjectDuplicationModel             $taskProjectDuplicationModel
 * \Kanboard\Model\TaskProjectMoveModel                    $taskProjectMoveModel
 * \Kanboard\Model\TaskRecurrenceModel                     $taskRecurrenceModel
 * \Kanboard\Model\TaskExternalLinkModel                   $taskExternalLinkModel
 * \Kanboard\Model\TaskFinderModel                         $taskFinderModel
 * \Kanboard\Model\TaskLinkModel                           $taskLinkModel
 * \Kanboard\Model\TaskModificationModel                   $taskModificationModel
 * \Kanboard\Model\TaskPositionModel                       $taskPositionModel
 * \Kanboard\Model\TaskStatusModel                         $taskStatusModel
 * \Kanboard\Model\TaskTagModel                            $taskTagModel
 * \Kanboard\Model\TaskMetadataModel                       $taskMetadataModel
 * \Kanboard\Model\TimezoneModel                           $timezoneModel
 * \Kanboard\Model\TransitionModel                         $transitionModel
 * \Kanboard\Model\UserModel                               $userModel
 * \Kanboard\Model\UserLockingModel                        $userLockingModel
 * \Kanboard\Model\UserNotificationModel                   $userNotificationModel
 * \Kanboard\Model\UserNotificationTypeModel               $userNotificationTypeModel
 * \Kanboard\Model\UserNotificationFilterModel             $userNotificationFilterModel
 * \Kanboard\Model\UserUnreadNotificationModel             $userUnreadNotificationModel
 * \Kanboard\Model\UserMetadataModel                       $userMetadataModel
 * \Kanboard\Pagination\DashboardPagination                $dashboardPagination
 * \Kanboard\Pagination\ProjectPagination                  $projectPagination
 * \Kanboard\Pagination\TaskPagination                     $taskPagination
 * \Kanboard\Pagination\SubtaskPagination                  $subtaskPagination
 * \Kanboard\Pagination\UserPagination                     $userPagination
 * \Kanboard\Validator\ActionValidator                     $actionValidator
 * \Kanboard\Validator\AuthValidator                       $authValidator
 * \Kanboard\Validator\ColumnValidator                     $columnValidator
 * \Kanboard\Validator\CategoryValidator                   $categoryValidator
 * \Kanboard\Validator\ColumnRestrictionValidator          $columnRestrictionValidator
 * \Kanboard\Validator\ColumnMoveRestrictionValidator      $columnMoveRestrictionValidator
 * \Kanboard\Validator\CommentValidator                    $commentValidator
 * \Kanboard\Validator\CurrencyValidator                   $currencyValidator
 * \Kanboard\Validator\CustomFilterValidator               $customFilterValidator
 * \Kanboard\Validator\ExternalLinkValidator               $externalLinkValidator
 * \Kanboard\Validator\GroupValidator                      $groupValidator
 * \Kanboard\Validator\LinkValidator                       $linkValidator
 * \Kanboard\Validator\PasswordResetValidator              $passwordResetValidator
 * \Kanboard\Validator\ProjectValidator                    $projectValidator
 * \Kanboard\Validator\ProjectRoleValidator                $projectRoleValidator
 * \Kanboard\Validator\SubtaskValidator                    $subtaskValidator
 * \Kanboard\Validator\SwimlaneValidator                   $swimlaneValidator
 * \Kanboard\Validator\TagValidator                        $tagValidator
 * \Kanboard\Validator\TaskLinkValidator                   $taskLinkValidator
 * \Kanboard\Validator\TaskValidator                       $taskValidator
 * \Kanboard\Validator\UserValidator                       $userValidator
 * \Kanboard\Validator\PredefinedTaskDescriptionValidator  $predefinedTaskDescriptionValidator
 * \Kanboard\Import\UserImport                             $userImport
 * \Kanboard\Export\SubtaskExport                          $subtaskExport
 * \Kanboard\Export\TaskExport                             $taskExport
 * \Kanboard\Export\TransitionExport                       $transitionExport
 * \Kanboard\Core\Filter\QueryBuilder                      $projectGroupRoleQuery
 * \Kanboard\Core\Filter\QueryBuilder                      $projectUserRoleQuery
 * \Kanboard\Core\Filter\QueryBuilder                      $projectActivityQuery
 * \Kanboard\Core\Filter\QueryBuilder                      $userQuery
 * \Kanboard\Core\Filter\QueryBuilder                      $projectQuery
 * \Kanboard\Core\Filter\QueryBuilder                      $taskQuery
 * \Kanboard\Core\Filter\LexerBuilder                      $taskLexer
 * \Kanboard\Core\Filter\LexerBuilder                      $projectActivityLexer
 * \Kanboard\Job\CommentEventJob                           $commentEventJob
 * \Kanboard\Job\SubtaskEventJob                           $subtaskEventJob
 * \Kanboard\Job\TaskEventJob                              $taskEventJob
 * \Kanboard\Job\TaskFileEventJob                          $taskFileEventJob
 * \Kanboard\Job\TaskLinkEventJob                          $taskLinkEventJob
 * \Kanboard\Job\ProjectFileEventJob                       $projectFileEventJob
 * \Kanboard\Job\NotificationJob                           $notificationJob
 * \Kanboard\Job\ProjectMetricJob                          $projectMetricJob
 * \Kanboard\Job\UserMentionJob                            $userMentionJob
 * \Psr\Log\LoggerInterface                                $logger
 * \PicoDb\Database                                        $db
 * \Symfony\Component\EventDispatcher\EventDispatcher      $dispatcher
 * \Symfony\Component\Console\Application                  $cli
 * \JsonRPC\Server                                         $api
 */

/**
 * Helper base class
 *
 * \Kanboard\Helper\AppHelper               $app
 * \Kanboard\Helper\AssetHelper             $asset
 * \Kanboard\Helper\AvatarHelper            $avatar
 * \Kanboard\Helper\BoardHelper             $board
 * \Kanboard\Helper\CommentHelper           $comment
 * \Kanboard\Helper\DateHelper              $dt
 * \Kanboard\Helper\FileHelper              $file
 * \Kanboard\Helper\FormHelper              $form
 * \Kanboard\Helper\HookHelper              $hook
 * \Kanboard\Helper\ModalHelper             $modal
 * \Kanboard\Helper\ModelHelper             $model
 * \Kanboard\Helper\SubtaskHelper           $subtask
 * \Kanboard\Helper\TaskHelper              $task
 * \Kanboard\Helper\TextHelper              $text
 * \Kanboard\Helper\UrlHelper               $url
 * \Kanboard\Helper\UserHelper              $user
 * \Kanboard\Helper\LayoutHelper            $layout
 * \Kanboard\Helper\ProjectRoleHelper       $projectRole
 * \Kanboard\Helper\ProjectHeaderHelper     $projectHeader
 * \Kanboard\Helper\ProjectActivityHelper   $projectActivity
 * \Kanboard\Helper\MailHelper              $mail
 */
