CREATE TABLE `master_sku_list` (
	`sku` VARCHAR(40) NOT NULL,
	`recommended` VARCHAR(40) NOT NULL,
	`syn_pn` VARCHAR(40) NULL DEFAULT NULL,
	`syn_cost` FLOAT(10,2) NULL DEFAULT NULL,
	`syn_qty` INT(11) NULL DEFAULT NULL,
	`td_pn` VARCHAR(40) NULL DEFAULT NULL,
	`td_cost` FLOAT(10,2) NULL DEFAULT NULL,
	`td_qty` INT(11) NULL DEFAULT NULL,
	`ing_pn` VARCHAR(40) NULL DEFAULT NULL,
	`ing_cost` FLOAT(10,2) NULL DEFAULT NULL,
	`ing_qty` INT(11) NULL DEFAULT NULL,
	`dh_pn` VARCHAR(40) NULL DEFAULT NULL,
	`dh_cost` FLOAT(10,2) NULL DEFAULT NULL,
	`dh_qty` INT(11) NULL DEFAULT NULL,
	`asi_pn` VARCHAR(40) NULL DEFAULT NULL,
	`asi_cost` FLOAT(10,2) NULL DEFAULT NULL,
	`asi_qty` INT(11) NULL DEFAULT NULL,
	`tak_pn` VARCHAR(40) NULL DEFAULT NULL,
	`tak_cost` FLOAT(10,2) NULL DEFAULT NULL,
	`tak_qty` INT(11) NULL DEFAULT NULL,
	`ep_pn` VARCHAR(40) NULL DEFAULT NULL,
	`ep_cost` FLOAT(10,2) NULL DEFAULT NULL,
	`ep_qty` INT(11) NULL DEFAULT NULL,
	`bte_pn` VARCHAR(40) NULL DEFAULT NULL,
	`bte_cost` FLOAT(10,2) NULL DEFAULT NULL,
	`bte_qty` INT(11) NULL DEFAULT NULL,
	`mfr` VARCHAR(40) NOT NULL,
	`upc` VARCHAR(40) NOT NULL,
	`mpn` VARCHAR(40) NOT NULL,
	`map_usd` FLOAT(10,2) NOT NULL,
	`map_cad` FLOAT(10,2) NOT NULL,
	`width` FLOAT(10,2) NOT NULL,
	`length` FLOAT(10,2) NOT NULL,
	`depth` FLOAT(10,2) NOT NULL,
	`weight` FLOAT(10,2) NOT NULL,
	`ca_ebay_blocked` TINYINT(4) NOT NULL,
	`us_ebay_blocked` TINYINT(4) NOT NULL,
	`ca_newegg_blocked` TINYINT(4) NOT NULL,
	`us_newegg_blocked` TINYINT(4) NOT NULL,
	`us_amazon_blocked` TINYINT(4) NOT NULL,
	`ca_amazon_blocked` TINYINT(4) NOT NULL,
	`uk_amazon_blocked` TINYINT(4) NOT NULL,
	`jp_amazon_blocked` TINYINT(4) NOT NULL,
	`mx_amazon_blocked` TINYINT(4) NOT NULL,
	`note` VARCHAR(40) NOT NULL,
	`name` VARCHAR(40) NOT NULL,
	`best_cost` FLOAT(10,2) NOT NULL,
	`overall_qty` INT(11) NOT NULL,
	PRIMARY KEY (`sku`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
